### ISSUE TITLE
No longer works with v1.0 JSON output from Postman v7.0.9

### ISSUE THREAD

**Issue by bakoontz** [aubm/postmanerator#53] opened 2019-05-01 18:41 UTC
As of Postman v. 7.0.9, parameter args are no longer parsed.  Output only includes CURL and HTTP request and response; no parameter descriptions are generated. 

Also, there is apparently no support for v2.0/v2.1 (v1.0 has been deprecated).  Docs don't reflect this (or is not easily found), would be cool if they did.

**Comment by aubm** [comment] 2019-05-02 19:35
Hey,

v0.9.0 has been released with support for collection v2.1.
It should work OK with the latest Postman exporting to 2.1.

Please provide feedback if you encounter any regressions.
Also note that support for collection v1 is dropped in v0.9.0.

**Comment by bakoontz** [comment] 2019-05-07 12:41
Appreciate that!

But maybe I'm just stupid, because I'm still not seeing anything other than some headers and a curl command.  Here's a really simple collection I created:

```
{
    "info": {
        "_postman_id": "13542a3e-14e0-407d-b43b-59b09286b393",
        "name": "Test collection",
        "description": "Test collection for postmanerator generation.",
        "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    "item": [
        {
            "name": "filedate",
            "request": {
                "method": "GET",
                "header": [],
                "body": {
                    "mode": "raw",
                    "raw": ""
                },
                "url": {
                    "raw": "http://localhost:8080/fileDate",
                    "protocol": "http",
                    "host": [
                        "localhost"
                    ],
                    "port": "8080",
                    "path": [
                        "fileDate"
                    ]
                },
                "description": "Get a filedate"
            },
            "response": []
        }
    ]
}
```
JSON output of REST call:
```
{"filedate":"22MAR19","note":"NOT FOR PRODUCTION USE (LOCAL)","queryTime":"0 ms"}
```
postmanerator invocation:
```
postmanerator.exe -collection Test_collection.postman_collection.json -output doc.html
Generating output... SUCCESS.
```
HTML output:
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test collection</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/monokai-sublime.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script>
        hljs.configure({
            tabReplace: '    ',
        });
        hljs.initHighlightingOnLoad();
    </script>
    <style>body {
    position: relative;
}

h1 {
    margin-top: 5px;
}

h1, h2, h3, h4 {
    color: #2b2b2b;
}

h2:after {
    content: ' ';
}

h5 {
    font-weight: bold;
}

h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {
    display: none;
    position: absolute;
    margin-left: 8px;
}

h1:hover a, h2:hover a, h3:hover a, h4:hover a, h5:hover a, h6:hover a {
    color: #a5a5a5;
    display: initial;
}

.nav.nav-tabs > li > a {
    padding-top: 4px;
    padding-bottom: 4px;

}

.tab-content {
    padding-top: 8px;
}

.table {
    margin-bottom: 8px;
}

pre {
    border-radius: 0px;
    border: none;
}

pre code {
    margin: -9.5px;
}

.request {
    margin-top: 12px;
    margin-bottom: 24px;
}

.response-text-sample {
    padding: 0px !important;
}

.response-text-sample pre {
    margin-bottom: 0px;
}


#sidebar-wrapper {
    z-index: 1000;
    position: fixed;
    left: 250px;
    width: 250px;
    height: 100%;
    margin-left: -250px;
    overflow-y: auto;
    overflow-x: hidden;
    background: #2b2b2b;
    padding-top: 20px;
}

#sidebar-wrapper ul {
    width: 250px;
}

#sidebar-wrapper ul li {
    margin-right: 10px;
#sidebar-wrapper ul li a:hover {
    background: inherit;
    text-decoration: none;
}

#sidebar-wrapper ul li a {
    display: block;
    color: #ECF0F1;
    padding: 6px 15px;
}

#sidebar-wrapper ul li ul {
    padding-left: 25px;
}

#sidebar-wrapper ul li ul li a {
    padding: 1px 0px;
}

#sidebar-wrapper ul li a:hover,
#sidebar-wrapper ul li a:focus {
    color: #e0c46c;
    border-right: solid 1px #e0c46c;
}

#sidebar-wrapper ul li.active > a {
    color: #e0c46c;
    border-right: solid 3px #e0c46c;
}

#sidebar-wrapper ul li:not(.active) ul {
    display: none;
}

#page-content-wrapper {
    width: 100%;
    position: absolute;
    padding: 15px 15px 15px 250px;
}
</style>
</head>
<body data-spy="scroll" data-target=".scrollspy">
<div id="sidebar-wrapper">
    <div class="scrollspy">
    <ul id="main-menu" data-spy="affix" class="nav">
        <li>
            <a href="#doc-general-notes">General notes</a>
        </li>

        <li>
            <a href="#doc-api-detail">API detail</a>
        </li>

        <li>
            <a href="#request-filedate">filedate</a>
        </li>


    </ul>
</div>

</div>
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Test collection</h1>

                <h2 id="doc-general-notes">
                    General notes
                    <a href="#doc-general-notes"><i class="glyphicon glyphicon-link"></i></a>
                </h2>

                <p>Test collection for postmanerator generation.</p>




                <h2 id="doc-api-detail">
                    API detail
                    <a href="#doc-api-detail"><i class="glyphicon glyphicon-link"></i></a>
                </h2>



                <div class="request">

                    <h3 id="request-filedate">
                        filedate
                        <a href="#request-filedate"><i class="glyphicon glyphicon-link"></i></a>
                    </h3>

                    <div></div>
                    <div>
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#request-filedate-example-curl" data-toggle="tab">Curl</a></li>
                            <li role="presentation"><a href="#request-filedate-example-http" data-toggle="tab">HTTP</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="request-filedate-example-curl">
                                <pre><code class="hljs curl">curl -X GET "http://localhost:8080/fileDate"</code></pre>
                            </div>
                            <div class="tab-pane" id="request-filedate-example-http">
                                <pre><code class="hljs http">GET /fileDate HTTP/1.1
Host: localhost:8080</code></pre>
                            </div>
                        </div>
                    </div>



                    <hr>
                </div>




            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-2.2.2.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function() {
        $("table:not(.table)").addClass('table table-bordered');
    });
</script>
</body>
</html>
```

**Comment by aubm** [comment] 2019-05-07 21:00
Looks good to me, the collection doesn't seem to have more to present.

Maybe try and provide your request with additional features like headers, a description, and a sample response, then export again through Postmanerator, the result should look better.

You could also generate a documentation out of the sample Postman Echo collection, to get an idea of what the default theme looks like.

**Closed by aubm** 2019-05-07 21:00 UTC
